#!/bin/sh

APPDIR=$(dirname "$0")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/robot_arm_remake_6df_0_02_pde.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-armv6hf.jar:$APPDIR/lib/gluegen-rt-natives-linux-armv6hf.jar:$APPDIR/lib/controlP5.jar:$APPDIR/lib/Arduino.jar:$APPDIR/lib/jssc.jar:$APPDIR/lib/serial.jar" robot_arm_remake_6df_0_02_pde "$@"
